namespace TMV.Common
{
  public class Constants
  {
    #region "Constructor"

    private static Constants _instance;
    private static System.Object _syncLock = new System.Object();

    protected Constants()
    {
    }

    public static Constants Instance()
    {
        if (_instance == null)
        {
            lock (_syncLock)
            {
                if (_instance == null)
                    _instance = new Constants();
            }
        }
        return _instance;
    }

    protected void Dispose()
    {
        _instance = null;
    }

    #endregion

    #region "Message"

    public string MESSAGE_COPY_SELECT_REQUIRE = "You have to select row to copy.";
    public string MESSAGE_DELETE_CONFIRM = "Are you sure to delete selected row?";
    public string MESSAGE_DELETE_SELECT_REQUIRE = "You have to select row to delete.";
    public string MESSAGE_DELETE_SUCCESS = "Data deleted";
    public string MESSAGE_DUPLICATED_RECORD = "Record duplicated.";
    public string MESSAGE_EDIT_SELECT_REQUIRE = "You have to select row to edit.";
    public string MESSAGE_EXPORT_OPEN_EXCEL_FILE_CONFIRM = "Exported successfully. Do you want to open the file?";
    public string MESSAGE_NO_DATA_FOUND = "No data found";
    public string MESSAGE_PERIOD_CLOSED = "You are not allowed to change data in closed period.";
    public string MESSAGE_SAVE_CONFIRM = "Do you want to save data?";
    public string MESSAGE_SAVE_SUCCESS = "Data saved";

    #endregion

    #region "Admin"

    public string APP_FORMBUTTONS_PKG_APP_FORMBUTTONS_DELETE = "APP_FORMBUTTONS_PKG_APP_FORMBUTTONS_Delete";
    public string APP_FORMBUTTONS_PKG_APP_FORMBUTTONS_GETALL = "APP_FORMBUTTONS_PKG_APP_FORMBUTTONS_GetAll";
    public string APP_FORMBUTTONS_PKG_APP_FORMBUTTONS_GETBYID = "APP_FORMBUTTONS_PKG_APP_FORMBUTTONS_GetByID";
    public string APP_FORMBUTTONS_PKG_APP_FORMBUTTONS_INSERT = "APP_FORMBUTTONS_PKG_APP_FORMBUTTONS_Insert";
    public string APP_FORMBUTTONS_PKG_APP_FORMBUTTONS_UPDATE = "APP_FORMBUTTONS_PKG_APP_FORMBUTTONS_Update";
    public string APP_FORMFUNCTIONS_PKG_APP_FORMFUNCTIONS_DELETE = "APP_FORMFUNCTIONS_PKG_APP_FORMFUNCTIONS_Delete";
    public string APP_FORMFUNCTIONS_PKG_APP_FORMFUNCTIONS_EDITITEM = "APP_FORMFUNCTIONS_PKG_APP_FORMFUNCTIONS_EditItem";
    public string APP_FORMFUNCTIONS_PKG_APP_FORMFUNCTIONS_GETALL = "APP_FORMFUNCTIONS_PKG_APP_FORMFUNCTIONS_GetAll";
    public string APP_FORMFUNCTIONS_PKG_APP_FORMFUNCTIONS_GETBYID = "APP_FORMFUNCTIONS_PKG_APP_FORMFUNCTIONS_GetByID";
    public string APP_FORMFUNCTIONS_PKG_APP_FORMFUNCTIONS_GETTREE = "APP_FORMFUNCTIONS_PKG_APP_FORMFUNCTIONS_GetTree";
    public string APP_FORMFUNCTIONS_PKG_APP_FORMFUNCTIONS_INSERT = "APP_FORMFUNCTIONS_PKG_APP_FORMFUNCTIONS_Insert";
    public string APP_FORMFUNCTIONS_PKG_APP_FORMFUNCTIONS_UPDATE = "APP_FORMFUNCTIONS_PKG_APP_FORMFUNCTIONS_Update";
    public string APP_FORMS_PKG_APP_FORMS_DELETE = "APP_FORMS_PKG_APP_FORMS_Delete";
    public string APP_FORMS_PKG_APP_FORMS_GETALL = "APP_FORMS_PKG_APP_FORMS_GetAll";
    public string APP_FORMS_PKG_APP_FORMS_GETBYID = "APP_FORMS_PKG_APP_FORMS_GetByID";
    public string APP_FORMS_PKG_APP_FORMS_GETBYMENUFORM = "APP_FORMS_PKG_APP_FORMS_GetByMenuForm";
    public string APP_FORMS_PKG_APP_FORMS_INSERT = "APP_FORMS_PKG_APP_FORMS_Insert";
    public string APP_FORMS_PKG_APP_FORMS_UPDATE = "APP_FORMS_PKG_APP_FORMS_Update";
    public string APP_GROUPFUNCTIONS_PKG_APP_GROUPFUNCTIONS_DELETE = "APP_GROUPFUNCTIONS_PKG_APP_GROUPFUNCTIONS_Delete";
    public string APP_GROUPFUNCTIONS_PKG_APP_GROUPFUNCTIONS_GETALL = "APP_GROUPFUNCTIONS_PKG_APP_GROUPFUNCTIONS_GetAll";
    public string APP_GROUPFUNCTIONS_PKG_APP_GROUPFUNCTIONS_GETBYGROUP = "APP_GROUPFUNCTIONS_PKG_APP_GROUPFUNCTIONS_GetByGroup";
    public string APP_GROUPFUNCTIONS_PKG_APP_GROUPFUNCTIONS_GETBYID = "APP_GROUPFUNCTIONS_PKG_APP_GROUPFUNCTIONS_GetByID";
    public string APP_GROUPFUNCTIONS_PKG_APP_GROUPFUNCTIONS_INSERT = "APP_GROUPFUNCTIONS_PKG_APP_GROUPFUNCTIONS_Insert";
    public string APP_GROUPFUNCTIONS_PKG_APP_GROUPFUNCTIONS_UPDATE = "APP_GROUPFUNCTIONS_PKG_APP_GROUPFUNCTIONS_Update";
    public string APP_GROUPS_PKG_APP_GROUPS_DELETE = "APP_GROUPS_PKG_APP_GROUPS_Delete";
    public string APP_GROUPS_PKG_APP_GROUPS_GETALL = "APP_GROUPS_PKG_APP_GROUPS_GetAll";
    public string APP_GROUPS_PKG_APP_GROUPS_GETBYID = "APP_GROUPS_PKG_APP_GROUPS_GetByID";
    public string APP_GROUPS_PKG_APP_GROUPS_INSERT = "APP_GROUPS_PKG_APP_GROUPS_Insert";
    public string APP_GROUPS_PKG_APP_GROUPS_UPDATE = "APP_GROUPS_PKG_APP_GROUPS_Update";
    public string APP_LOGBOOK_PKG_APP_LOGBOOK_DELETE = "APP_LOGBOOK_PKG_APP_LOGBOOK_Delete";
    public string APP_LOGBOOK_PKG_APP_LOGBOOK_GETALL = "APP_LOGBOOK_PKG_APP_LOGBOOK_GetAll";
    public string APP_LOGBOOK_PKG_APP_LOGBOOK_GETBYID = "APP_LOGBOOK_PKG_APP_LOGBOOK_GetByID";
    public string APP_LOGBOOK_PKG_APP_LOGBOOK_INSERT = "APP_LOGBOOK_PKG_APP_LOGBOOK_Insert";
    public string APP_LOGBOOK_PKG_APP_LOGBOOK_SEARCH = "APP_LOGBOOK_PKG_APP_LOGBOOK_Search";
    public string APP_LOGBOOK_PKG_APP_LOGBOOK_UPDATE = "APP_LOGBOOK_PKG_APP_LOGBOOK_Update";
    public string APP_USERGROUP_PKG_APP_USERGROUP_DELETE = "APP_USERGROUP_PKG_APP_USERGROUP_Delete";
    public string APP_USERGROUP_PKG_APP_USERGROUP_GETALL = "APP_USERGROUP_PKG_APP_USERGROUP_GetAll";
    public string APP_USERGROUP_PKG_APP_USERGROUP_GETBYGROUP = "APP_USERGROUP_PKG_APP_USERGROUP_GetByGroup";
    public string APP_USERGROUP_PKG_APP_USERGROUP_GETBYID = "APP_USERGROUP_PKG_APP_USERGROUP_GetByID";
    public string APP_USERGROUP_PKG_APP_USERGROUP_GETBYUSER = "APP_USERGROUP_PKG_APP_USERGROUP_GetByUser";
    public string APP_USERGROUP_PKG_APP_USERGROUP_INSERT = "APP_USERGROUP_PKG_APP_USERGROUP_Insert";
    public string APP_USERGROUP_PKG_APP_USERGROUP_UPDATE = "APP_USERGROUP_PKG_APP_USERGROUP_Update";
    public string APP_USERS_PKG_APP_USERS_ACCOUNTPOLICY = "APP_USERS_PKG_APP_USERS_POLICY";
    public string APP_USERS_PKG_APP_USERS_CHANGEPASSWORD = "APP_USERS_PKG_APP_USERS_SetPassword";
    public string APP_USERS_PKG_APP_USERS_DELETE = "APP_USERS_PKG_APP_USERS_Delete";
    public string APP_USERS_PKG_APP_USERS_GETALL = "APP_USERS_PKG_APP_USERS_GetAll";
    public string APP_USERS_PKG_APP_USERS_GETBYID = "APP_USERS_PKG_APP_USERS_GetByID";
    public string APP_USERS_PKG_APP_USERS_GETBYUSERNAME = "APP_USERS_PKG_APP_USERS_GETBYUSERNAME";
    public string APP_USERS_PKG_APP_USERS_GETUSERBUTTON = "APP_USERS_PKG_APP_USERS_GetUserButton";
    public string APP_USERS_PKG_APP_USERS_GETUSERGROUP = "APP_USERS_PKG_APP_USERS_GetUserGroup";
    public string APP_USERS_PKG_APP_USERS_GETUSERMENU = "APP_USERS_PKG_APP_USERS_GetUserMenu";
    public string APP_USERS_PKG_APP_USERS_INSERT = "APP_USERS_PKG_APP_USERS_Insert";
    public string APP_USERS_PKG_APP_USERS_ISEXPIREDPASSWORD = "APP_USERS_PKG_APP_USERS_EXPIRED";
    public string APP_USERS_PKG_APP_USERS_UPDATE = "APP_USERS_PKG_APP_USERS_Update";
    public string APP_USERS_PKG_APP_USERS_UpdateFailed = "APP_USERS_PKG_APP_USERS_UpdateFailed";
    public string APP_USERS_PKG_APP_USERS_USERCHANGEPASSWORD = "APP_USERS_PKG_APP_USERS_UserSetPassword";
    public string APP_DOMAIN_PKG_APP_MASTER_DOMAIN_DELETE = "APP_MASTER_DOMAIN_PKG_APP_MASTER_DOMAIN_Delete";
    public string APP_DOMAIN_PKG_APP_MASTER_DOMAIN_GETALL = "APP_MASTER_DOMAIN_PKG_APP_MASTER_DOMAIN_GetAll";
    public string APP_DOMAIN_PKG_APP_MASTER_DOMAIN_GETBYDOMAIN = "APP_MASTER_DOMAIN_PKG_APP_MASTER_DOMAIN_GetByDomain";
    public string APP_DOMAIN_PKG_APP_MASTER_DOMAIN_GETBYID = "APP_MASTER_DOMAIN_PKG_APP_MASTER_DOMAIN_GetByID";
    public string APP_DOMAIN_PKG_APP_MASTER_DOMAIN_GETBYITEM = "APP_MASTER_DOMAIN_PKG_APP_MASTER_DOMAIN_GetByItem";
    public string APP_DOMAIN_PKG_APP_MASTER_DOMAIN_INSERT = "APP_MASTER_DOMAIN_PKG_APP_MASTER_DOMAIN_Insert";
    public string APP_DOMAIN_PKG_APP_MASTER_DOMAIN_SEARCH = "APP_MASTER_DOMAIN_PKG_APP_MASTER_DOMAIN_Search";
    public string APP_DOMAIN_PKG_APP_MASTER_DOMAIN_UPDATE = "APP_MASTER_DOMAIN_PKG_APP_MASTER_DOMAIN_Update";

    #endregion

    #region "MST"
    public string MST_DOMAIN_PKG_APP_MASTER_DOMAIN_DELETE = "APP_MASTER_DOMAIN_PKG_APP_MASTER_DOMAIN_Delete";
    public string MST_DOMAIN_PKG_APP_MASTER_DOMAIN_GETALL = "APP_MASTER_DOMAIN_PKG_APP_MASTER_DOMAIN_GetAll";
    public string MST_DOMAIN_PKG_APP_MASTER_DOMAIN_GETBYDOMAIN = "APP_MASTER_DOMAIN_PKG_APP_MASTER_DOMAIN_GetByDomain";
    public string MST_DOMAIN_PKG_APP_MASTER_DOMAIN_GETBYID = "APP_MASTER_DOMAIN_PKG_APP_MASTER_DOMAIN_GetByID";
    public string MST_DOMAIN_PKG_APP_MASTER_DOMAIN_GETBYITEM = "APP_MASTER_DOMAIN_PKG_APP_MASTER_DOMAIN_GetByItem";
    public string MST_DOMAIN_PKG_APP_MASTER_DOMAIN_INSERT = "APP_MASTER_DOMAIN_PKG_APP_MASTER_DOMAIN_Insert";
    public string MST_DOMAIN_PKG_APP_MASTER_DOMAIN_SEARCH = "APP_MASTER_DOMAIN_PKG_APP_MASTER_DOMAIN_Search";
    public string MST_DOMAIN_PKG_APP_MASTER_DOMAIN_UPDATE = "APP_MASTER_DOMAIN_PKG_APP_MASTER_DOMAIN_Update";

    public string MST_GRADE_COLOR_PKG_MST_GRADE_COLOR_DELETE = "MST_GRADE_COLOR_PKG_MST_GRADE_COLOR_Delete";
    public string MST_GRADE_COLOR_PKG_MST_GRADE_COLOR_DELETEBYID = "MST_GRADE_COLOR_PKG_MST_GRADE_COLOR_DeleteByID";
    public string MST_GRADE_COLOR_PKG_MST_GRADE_COLOR_GETALL = "MST_GRADE_COLOR_PKG_MST_GRADE_COLOR_GetAll";
    public string MST_GRADE_COLOR_PKG_MST_GRADE_COLOR_GETBYGRADEID = "MST_GRADE_COLOR_PKG_MST_GRADE_COLOR_GetByGradeId";
    public string MST_GRADE_COLOR_PKG_MST_GRADE_COLOR_GETBYID = "MST_GRADE_COLOR_PKG_MST_GRADE_COLOR_GetByID";
    public string MST_GRADE_COLOR_PKG_MST_GRADE_COLOR_INSERT = "MST_GRADE_COLOR_PKG_MST_GRADE_COLOR_Insert";
    public string MST_GRADE_COLOR_PKG_MST_GRADE_COLOR_SEARCH = "MST_GRADE_COLOR_PKG_MST_GRADE_COLOR_Search";
    public string MST_GRADE_COLOR_PKG_MST_GRADE_COLOR_UPDATE = "MST_GRADE_COLOR_PKG_MST_GRADE_COLOR_Update";
    public string MST_GRADE_COLOR_PKG_MST_GRADE_COLOR_VIEWALL = "MST_GRADE_COLOR_PKG_MST_GRADE_COLOR_ViewAll";

    public string MST_COLOR_PKG_MST_COLOR_DELETE = "MST_COLOR_PKG_MST_COLOR_Delete";
    public string MST_COLOR_PKG_MST_COLOR_GETALL = "MST_COLOR_PKG_MST_COLOR_GetAll";
    public string MST_COLOR_PKG_MST_COLOR_GETBYID = "MST_COLOR_PKG_MST_COLOR_GetByID";
    public string MST_COLOR_PKG_MST_COLOR_INSERT = "MST_COLOR_PKG_MST_COLOR_Insert";
    public string MST_COLOR_PKG_MST_COLOR_SEARCH = "MST_COLOR_PKG_MST_COLOR_Search";
    public string MST_COLOR_PKG_MST_COLOR_UPDATE = "MST_COLOR_PKG_MST_COLOR_Update";

    public string MST_MODEL_PKG_MST_MODEL_DELETE = "MST_MODEL_PKG_MST_MODEL_Delete";
    public string MST_MODEL_PKG_MST_MODEL_GETALL = "MST_MODEL_PKG_MST_MODEL_GetAll";
    public string MST_MODEL_PKG_MST_MODEL_GETBYID = "MST_MODEL_PKG_MST_MODEL_GetByID";
    public string MST_MODEL_PKG_MST_MODEL_INSERT = "MST_MODEL_PKG_MST_MODEL_Insert";
    public string MST_MODEL_PKG_MST_MODEL_SEARCH = "MST_MODEL_PKG_MST_MODEL_Search";
    public string MST_MODEL_PKG_MST_MODEL_UPDATE = "MST_MODEL_PKG_MST_MODEL_Update";

    public string MST_MODEL_GRADE_PKG_MST_MODEL_GRADE_DELETE = "MST_MODEL_GRADE_PKG_MST_MODEL_GRADE_Delete";
    public string MST_MODEL_GRADE_PKG_MST_MODEL_GRADE_GETALL = "MST_MODEL_GRADE_PKG_MST_MODEL_GRADE_GetAll";
    public string MST_MODEL_GRADE_PKG_MST_MODEL_GRADE_GETBYID = "MST_MODEL_GRADE_PKG_MST_MODEL_GRADE_GetByID";
    public string MST_MODEL_GRADE_PKG_MST_MODEL_GRADE_INSERT = "MST_MODEL_GRADE_PKG_MST_MODEL_GRADE_Insert";
    public string MST_MODEL_GRADE_PKG_MST_MODEL_GRADE_SEARCH = "MST_MODEL_GRADE_PKG_MST_MODEL_GRADE_Search";
    public string MST_MODEL_GRADE_PKG_MST_MODEL_GRADE_UPDATE = "MST_MODEL_GRADE_PKG_MST_MODEL_GRADE_Update";

    public string MST_LOTCODE_GRADE_PKG_MST_LOTCODE_GRADE_DELETE = "MST_LOTCODE_GRADE_PKG_MST_LOTCODE_GRADE_Delete";
    public string MST_LOTCODE_GRADE_PKG_MST_LOTCODE_GRADE_GETALL = "MST_LOTCODE_GRADE_PKG_MST_LOTCODE_GRADE_GetAll";
    public string MST_LOTCODE_GRADE_PKG_MST_LOTCODE_GRADE_GETBYID = "MST_LOTCODE_GRADE_PKG_MST_LOTCODE_GRADE_GetByID";
    public string MST_LOTCODE_GRADE_PKG_MST_LOTCODE_GRADE_GETBYMODELID = "MST_LOTCODE_GRADE_PKG_MST_LOTCODE_GRADE_GetByModelId";
    public string MST_LOTCODE_GRADE_PKG_MST_LOTCODE_GRADE_GETMODEL = "MST_LOTCODE_GRADE_PKG_MST_LOTCODE_GRADE_GetModel";
    public string MST_LOTCODE_GRADE_PKG_MST_LOTCODE_GRADE_INSERT = "MST_LOTCODE_GRADE_PKG_MST_LOTCODE_GRADE_Insert";
    public string MST_LOTCODE_GRADE_PKG_MST_LOTCODE_GRADE_SEARCH = "MST_LOTCODE_GRADE_PKG_MST_LOTCODE_GRADE_Search";
    public string MST_LOTCODE_GRADE_PKG_MST_LOTCODE_GRADE_UPDATE = "MST_LOTCODE_GRADE_PKG_MST_LOTCODE_GRADE_Update";
    #endregion
  }
}